Update baseConfig.js
needed to add PLATFORM.location.origin to support ssr with aurelia

this will resolve this : 

Error: Error invoking BaseConfig. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: window is not defined
Inner Error Stack:
ReferenceError: window is not defined